import os
import sys
from src.exception import CustomException
from src.logger import logging

import pandas as pd
from sklearn.model_selection import train_test_split
from dataclasses import dataclass

# Import subsequent components for the full pipeline execution
from src.components.data_transformation import DataTransformation
from src.components.data_transformation import DataTransformationConfig
from src.components.model_trainer import ModelTrainer

# 1. Configuration Class
# @dataclass is used here to efficiently store path variables. 
# It's cleaner than a standard class when you only need to store data/constants.
@dataclass
class DataIngestionConfig:
    # We define where the raw, train, and test CSV files will be stored.
    # 'artifacts' is a common folder name for outputs generated by the pipeline.
    train_data_path: str = os.path.join('artifacts', "train.csv")
    test_data_path: str = os.path.join('artifacts', "test.csv")
    raw_data_path: str = os.path.join('artifacts', "data.csv")
    
class DataIngestion:
    def __init__(self):
        # When DataIngestion is initialized, it creates its own config object.
        self.ingestion_config = DataIngestionConfig()
        
    def initiate_data_ingestion(self):
        """
        Logic: 
        1. Read local CSV -> 2. Save Raw copy -> 3. Split Data -> 4. Save Train/Test copies
        """
        logging.info("Entered the data ingestion method or components")
        try:
            # Step 2. Reading the dataset
            # You can change this to read from a Database (MongoDB/SQL) or a Cloud URL.
            df = pd.read_csv("notebook/data/stud.csv")
            logging.info("Successfully read the dataset as a dataframe")
            
            # Step 3. Directory Creation
            # os.makedirs ensures the 'artifacts' folder exists before we try to save files into it.
            # exist_ok=True prevents errors if the folder already exists.
            os.makedirs(os.path.dirname(self.ingestion_config.train_data_path), exist_ok=True)
            
            # Save the full, unsplit data to the 'raw_data_path' (artifacts/data.csv)
            df.to_csv(self.ingestion_config.raw_data_path, index=False, header=True)
            
            # Step 4. Train-Test Split
            # Splitting 80% for training and 20% for testing.
            logging.info("Train test split initiated")
            train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)
            
            # Step 5. Exporting split datasets
            # Saving the processed splits so the 'Data Transformation' component can access them.
            train_set.to_csv(self.ingestion_config.train_data_path, index=False, header=True)
            test_set.to_csv(self.ingestion_config.test_data_path, index=False, header=True)
            
            logging.info("Ingestion of the data is completed")
            
            # Return the file paths to be used by the DataTransformation component
            return (
                self.ingestion_config.train_data_path,
                self.ingestion_config.test_data_path,
            )
        except Exception as e:
            # CustomException captures the error and the line number from 'sys'
            raise CustomException(e, sys)
            

# Execution block to test the full pipeline
if __name__=="__main__":
    # STAGE 1: Data Ingestion
    obj = DataIngestion()
    train_data, test_data = obj.initiate_data_ingestion()
    
    # STAGE 2: Data Transformation (Handling missing values, Scaling, Encoding)
    data_transformation = DataTransformation()
    # This returns NumPy arrays (train_arr, test_arr) which are ready for Model Training
    train_arr, test_arr, _ = data_transformation.initiate_data_transformation(train_data, test_data)
    
    # STAGE 3: Model Training
    # Passing the arrays into the ModelTrainer class we defined earlier
    modeltrainer = ModelTrainer()
    print(modeltrainer.initiate_model_trainer(train_arr, test_arr))